apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ipman-webhook-certificate
  namespace: ipman-system
spec:
  commonName: ipman-webhook-service.ipman-system.svc
  dnsNames:
    - ipman-webhook-service.ipman-system.svc
    - ipman-webhook-service.ipman-system.svc.cluster.local
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: ipman-webhook-cert-secret
