apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ipman
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ipman
    app.kubernetes.io/version: 1.16.0
    control-plane: controller-manager
    helm.sh/chart: ipman-0.1.15
  name: ipman
  namespace: ipman-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ipman
      app.kubernetes.io/name: ipman
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ipman
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ipman
        app.kubernetes.io/version: 1.16.0
        control-plane: controller-manager
        helm.sh/chart: ipman-0.1.15
    spec:
      containers:
        - env:
            - name: NAMESPACE_NAME
              value: ipman-system
            - name: XFRMINION_IMAGE
              value: 192.168.10.201:5000/xfrminion:latest-dev
            - name: VXLANDLORD_IMAGE
              value: 192.168.10.201:5000/vxlandlord:latest-dev
            - name: RESTCTL_IMAGE
              value: 192.168.10.201:5000/restctl:latest-dev
            - name: XFRMINJECTOR_IMAGE
              value: 192.168.10.201:5000/xfrminjector:latest-dev
            - name: CHARONDAEMON_IMAGE
              value: 192.168.10.201:5000/charon:latest-dev
            - name: CADDY_IMAGE
              value: caddy:2.10.0-alpine
            - name: PROXY_SOCKET_PATH
              value: /var/run/ipman
            - name: HOST_SOCKETS_PATH
              value: /var/run/ipman
            - name: XFRMINION_PULL_POLICY
              value: Always
            - name: XFRMINJECTOR_PULL_POLICY
              value: Always
            - name: XFRMINJECTOR_TTL_SECONDS
              value: "120"
            - name: CHARON_PULL_POLICY
              value: Always
            - name: RESTCTL_PULL_POLICY
              value: Always
            - name: PROXY_PULL_POLICY
              value: IfNotPresent
            - name: POD_WAIT_TIMEOUT
              value: "60"
            - name: MONITORING_ENABLED
              value: "true"
            - name: MONITORING_SCRAPE_INTERVAL
              value: 10s
            - name: MONITORING_RELEASE_NAME
              value: kps
          image: 192.168.10.201:5000/operator:latest-dev
          imagePullPolicy: Always
          name: ipman
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: webhook-certs
              readOnly: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: ipman-service-account
      volumes:
        - name: webhook-certs
          secret:
            secretName: ipman-webhook-cert-secret
