apiVersion: apps/v1
kind: Deployment
metadata:
  name: scb-sip
  namespace: ipman
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: scb-sip
  template:
    metadata:
      annotations:
        vlanman.dialo.ai/network: scb-sip-vlan
        vlanman.dialo.ai/pool: primary
      labels:
        app.kubernetes.io/name: scb-sip
    spec:
      containers:
        - env:
            - name: EIO_BACKEND
              value: io-uring
          image: nginx
          imagePullPolicy: IfNotPresent
          name: traffic-controller
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /recordings/wav
              name: wav
            - mountPath: /recordings/rtp
              name: rtp
        - image: nginx
          name: recorder
          volumeMounts:
            - mountPath: /recordings/wav
              name: wav
            - mountPath: /recordings/rtp
              name: rtp
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: wav
        - emptyDir: {}
          name: rtp
