apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-controller-best
  namespace: ipman
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: traffic-controller-best
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        ipman.dialo.ai/childName: sip
        ipman.dialo.ai/ipmanName: best
        ipman.dialo.ai/poolName: sip
      labels:
        app.kubernetes.io/name: traffic-controller-best
    spec:
      containers:
        - env:
            - name: EIO_BACKEND
              value: io-uring
          image: nginx
          name: traffic-controller
          resources:
            limits:
              memory: 200M
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /recordings
              name: recordings
      volumes:
        - emptyDir: {}
          name: recordings
