apiVersion: v1
kind: Service
metadata:
  name: allegro-sftp
  namespace: ipman
spec:
  ports:
    - name: production
      port: 22
      protocol: TCP
      targetPort: 2222
    - name: test
      port: 23
      protocol: TCP
      targetPort: 2223
  selector:
    dialo.ai/proxy-target: allegro
