apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: switch-proxy
spec:
  mappings:
    - interfaceName: enp9s0f1np1
      nodeName: astor-0
    - interfaceName: enp9s0f1np1
      nodeName: astor-1
    - interfaceName: enp9s0f1np1
      nodeName: astor-2
    - interfaceName: vrack
      nodeName: hgrai1-0
    - interfaceName: vrack
      nodeName: hgrai1-1
    - interfaceName: vrack
      nodeName: scalea6-0
    - interfaceName: vrack
      nodeName: scalea6-1
  pools:
    - addresses:
        - 192.168.100.173/24
      description: Primary IP pool
      name: primary
      routes: []
  vlanId: 2
