apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: scb-sip-vlan
spec:
  managerAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - hgrai1-1
                  - scalea6-0
                  - scalea6-1
              - key: dialo.ai/virtualized
                operator: NotIn
                values:
                  - "true"
  mappings:
    - interfaceName: enp9s0f1np1
      nodeName: astor-0
    - interfaceName: enp9s0f1np1
      nodeName: astor-1
    - interfaceName: enp9s0f1np1
      nodeName: astor-2
    - interfaceName: vrack
      nodeName: hgrai1-0
    - interfaceName: vrack
      nodeName: hgrai1-1
    - interfaceName: vrack
      nodeName: scalea6-0
    - interfaceName: vrack
      nodeName: scalea6-1
  pools:
    - addresses:
        - 10.93.80.130/24
      description: Primary IP pool
      name: primary
      routes:
        - dest: 10.93.255.66/32
          scopeLink: true
          src: self
        - dest: 10.93.148.23/32
          src: none
          via: 10.93.255.66
  vlanId: 100
