apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vlanman-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vlanman-cluster-resource-access
subjects:
  - kind: ServiceAccount
    name: vlanman-service-account
    namespace: vlanman-system
