apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vlanman-cluster-resource-access
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - vlanman.dialo.ai
    resources:
      - vlannetworks
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - vlanman.dialo.ai
    resources:
      - vlannetworks/status
    verbs:
      - create
      - get
      - patch
      - update
