apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vlannetworks.vlanman.dialo.ai
spec:
  group: vlanman.dialo.ai
  names:
    kind: VlanNetwork
    plural: vlannetworks
    shortNames:
      - vlan
    singular: vlannetwork
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.vlanId
          name: VLAN ID
          type: integer
        - jsonPath: .spec.gatewayIp
          name: Gateway IP
          type: string
        - jsonPath: .status.active
          name: Active
          type: boolean
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                excludedNodes:
                  items:
                    type: string
                  type: array
                localGatewayIp:
                  type: string
                localSubnet:
                  items:
                    type: string
                  type: array
                mappings:
                  items:
                    properties:
                      interfaceName:
                        type: string
                      nodeName:
                        type: string
                    type: object
                  type: array
                pools:
                  items:
                    properties:
                      addresses:
                        items:
                          type: string
                        type: array
                      description:
                        type: string
                      name:
                        type: string
                    type: object
                  type: array
                remoteGatewayIp:
                  type: string
                remoteSubnet:
                  items:
                    type: string
                  type: array
                vlanId:
                  type: integer
              required:
                - remoteSubnet
                - localSubnet
                - vlanId
                - pools
              type: object
            status:
              properties:
                freeIPs:
                  additionalProperties:
                    items:
                      type: string
                    type: array
                  type: object
                pendingIPs:
                  additionalProperties:
                    additionalProperties:
                      type: string
                    type: object
                  type: object
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
