apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: test-vlan2
spec:
  pools:
    - addresses:
        - 10.1.7.3/24
        - 10.1.7.8/24
      description: dupa
      name: primary
      routes: []
  vlanId: 2
