apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scb-web
  namespace: argocd
spec:
  destination:
    namespace: external-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/prod/scb-web
    repoURL: https://github.com/plan9better/argo
    targetRevision: master
